server:
  port: 9000

spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorization-server:
        issuer: http://localhost:9000

logging:
  level:
    org.springframework.security: DEBUG
