server:
  port: 8081

spring:
  application:
    name: javabooks-app
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:javabooksdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
